import { defineConfig } from 'unocss';
import presetAttributify from '@unocss/preset-attributify';
import presetIcons from '@unocss/preset-icons';
import { presetForms } from '@julr/unocss-preset-forms';
import presetUno from '@unocss/preset-uno';
import presetAnimations from 'unocss-preset-animations';

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons(),
    presetForms(),
    presetAnimations(),
  ],
  theme: {
    fontFamily: {
      sans: 'Tajawal, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    },
    colors: {
      primary: '#06b6d4',
      secondary: '#a855f7',
      accent: '#facc15',
      background: '#ffffff',
      text: '#0f172a',
      muted: '#64748b',
      border: '#e2e8f0',
      white: '#ffffff',
      black: '#000000',
      transparent: 'transparent',
      current: 'currentColor',
      error: '#ef4444',
      success: '#22c55e',
      warning: '#f59e0b',
      info: '#3b82f6',
    },
  },
  shortcuts: {
    'centered': 'flex items-center justify-center',
    'column': 'flex flex-col',
    'row': 'flex flex-row',
    'layout-base': 'bg-white',
    'layout-container': 'bg-white',
    'btn': 'py-2 px-4 font-medium rounded-xl focus:outline-none transition-all shadow-sm',
    'btn-primary': 'bg-primary text-white hover:bg-primary/90 active:bg-primary/80',
    'btn-secondary': 'bg-secondary text-white hover:bg-secondary/90 active:bg-secondary/80',
    'btn-accent': 'bg-accent text-text hover:bg-accent/90 active:bg-accent/80',
    'btn-outline': 'border-2 border-primary text-primary hover:bg-primary/10',
    'btn-light': 'bg-white text-primary hover:bg-primary/5',
    'btn-success': 'bg-success text-white hover:bg-success/90',
    'card': 'rounded-xl shadow-sm bg-white overflow-hidden border border-border transition-all',
    'card-hover': 'hover:shadow-md hover:translate-y-[-2px] transition-all duration-300',
    'card-container': 'bg-white rounded-xl p-4',
    'card-header': 'p-4 border-b border-border font-medium text-primary',
    'card-body': 'p-4',
    'card-footer': 'p-4 border-t border-border',
    'section': 'p-6 rounded-xl',
    'section-light': 'bg-primary/5',
    'section-card': 'bg-secondary/5',
    'input': 'rounded-lg border border-border px-3 py-2 focus:border-primary focus:ring-2 focus:ring-primary/30 bg-white text-text',
    'label': 'block mb-1 text-text font-medium',
    'text-heading': 'text-text font-medium tracking-tight',
    'text-body': 'text-text leading-relaxed',
    'text-muted': 'text-muted',
    'interactive': 'transition-all duration-200 ease-in-out',
    'interactive-hover': 'hover:shadow-md hover:translate-y-[-2px]',
    'animate-fade-in': 'opacity-0 animate-in fade-in',
    'animate-slide-in-left': 'opacity-0 animate-in slide-in-from-left',
    'animate-slide-in-right': 'opacity-0 animate-in slide-in-from-right',
    'animate-scale': 'opacity-0 scale-95 animate-in zoom-in',
    'animate-bounce-sm': 'animate-in',
    'theme-light': 'bg-white text-text',
    'light-shadow': 'shadow-[0_4px_6px_-1px_rgba(0,0,0,0.05),_0_2px_4px_-2px_rgba(0,0,0,0.03)]',
  },
  safelist: [
    'layout-base',
    'layout-container',
    'theme-light',
    'light-shadow',
    'animate-fade-in',
    'animate-slide-in-left',
    'animate-slide-in-right',
    'animate-scale',
    'animate-bounce-sm',
    'font-sans',
  ],
});
